'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Amsterdam.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _428px_Sights_in_Amsterdam2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("428px-Sights_in_Amsterdam2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property activity1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("activity1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property activity10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("activity10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property activity11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("activity11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property activity12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("activity12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property activity13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("activity13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property activity14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("activity14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property activity15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("activity15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property activity2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("activity2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property activity3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("activity3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property activity4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("activity4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property activity5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("activity5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property activity6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("activity6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property activity7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("activity7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property activity8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("activity8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property activity9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("activity9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Amsterdam_Airport_Schiphol_Front() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Amsterdam_Airport_Schiphol_Front", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Amsterdam_Bridge_thumb_500x330() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Amsterdam-Bridge-thumb-500x330", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Amsterdam_panorama() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Amsterdam_panorama", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bike_tour() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bike tour", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property canal_tours_boat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("canal-tours-boat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property canal_tours_boat1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("canal-tours-boat1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property euro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("euro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property euro1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("euro1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exterior() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exterior", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hallo() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("hallo", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property hoemaaktUhet() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("hoemaaktUhet", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Hotel_Map_Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hotel Map Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HotelMap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HotelMap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property koninklijkpaleis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("koninklijkpaleis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kuntUdatnogeens() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("kuntUdatnogeens", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property mainbackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mainbackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mainbackground1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mainbackground1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property manage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property manage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property manage5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manage5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property manege3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manege3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property manege4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manege4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nightwatch500() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nightwatch500", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property open_garden_days() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open-garden-days", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paleisopdedam_atlas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paleisopdedam-atlas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rijksmuseum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rijksmuseum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rijksmuseum2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rijksmuseum2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property transportation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transportation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windmill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windmill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
